import React from 'react'
import PropTypes from 'prop-types'
import MovieGrid from '../components/MovieGrid'
import Head from 'next/head'

Movie.propTypes = {}

function Movie() {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3
        style={{
          textAlign: 'center',
          color: '#fff',
          background: '#000',
          padding: '40px 0',
          fontSize: '40px',
        }}
      >
        MOVIES
      </h3>
      <MovieGrid type="movie" />
    </div>
  )
}

export default Movie
