import Head from 'next/head'
import React from 'react'
import MovieGrid from '../../components/MovieGrid'

TopRated.propTypes = {}

function TopRated() {
  return (
    <div>
      <Head>
        <title>Top Rated</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="movies"
        style={{
          paddingTop: '100px',
          background: '#000',
        }}
      >
        <h3
          style={{
            textAlign: 'center',
            color: '#fff',
            background: '#000',
            padding: '40px 0',
            fontSize: '40px',
          }}
        >
          TOP RATED MOVIES
        </h3>
        <MovieGrid type="movie" category="top_rated" />
      </div>
    </div>
  )
}

export default TopRated
