import Head from 'next/head'
import React from 'react'
import MovieGrid from '../../components/MovieGrid'

TVShows.propTypes = {}

function TVShows(props) {
  return (
    <div>
      <Head>
        <title>TV Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3
        style={{
          textAlign: 'center',
          color: '#fff',
          background: '#000',
          padding: '40px 0',
          fontSize: '40px',
        }}
      >
        TV SHOWS
      </h3>
      <MovieGrid type="tv" />
    </div>
  )
}

export default TVShows
