import Head from 'next/head'
import React from 'react'
import MovieGrid from '../../components/MovieGrid'
import SearchTV from './search'

TVShows.propTypes = {}

function TVShows(props) {
  return (
    <div>
      <Head>
        <title>TV Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="tv-shows" style={{ paddingTop: '100px', background: '#000' }}>
        <h3
          style={{
            textAlign: 'center',
            color: '#fff',
            background: '#000',
            padding: '40px 0',
            fontSize: '40px',
          }}
        >
          TV SHOWS
        </h3>
        <SearchTV />
        <MovieGrid type="tv" category="popular" />
      </div>
    </div>
  )
}

export default TVShows
